/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacmanGame;

import javax.swing.JButton;
/**
 *
 * @author Yossef
 */
public class Menu extends javax.swing.JPanel {
    public Menu() {
        initComponents();
    }
    public JButton getPlayButton() {
        return play;
    }
    public JButton getScoresButton() {
        return scores;
    }
    public JButton getHowToPlayButton() {
        return howToPlay;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        howToPlay = new javax.swing.JButton();
        scores = new javax.swing.JButton();

        setLayout(null);

        play.setBackground(new java.awt.Color(225, 225, 225));
        play.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        play.setForeground(new java.awt.Color(255, 255, 255));
        play.setText("Play");
        play.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        play.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                playMouseMoved(evt);
            }
        });
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        add(play);
        play.setBounds(180, 270, 170, 50);

        exit.setBackground(new java.awt.Color(225, 225, 225));
        exit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        add(exit);
        exit.setBounds(180, 500, 170, 50);

        howToPlay.setBackground(new java.awt.Color(225, 225, 225));
        howToPlay.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        howToPlay.setForeground(new java.awt.Color(255, 255, 255));
        howToPlay.setText("How to play");
        howToPlay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                howToPlayMouseMoved(evt);
            }
        });
        howToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToPlayActionPerformed(evt);
            }
        });
        add(howToPlay);
        howToPlay.setBounds(180, 350, 170, 50);

        scores.setBackground(new java.awt.Color(225, 225, 225));
        scores.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        scores.setForeground(new java.awt.Color(255, 255, 255));
        scores.setText("Scores");
        scores.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                scoresMouseMoved(evt);
            }
        });
        scores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoresActionPerformed(evt);
            }
        });
        add(scores);
        scores.setBounds(180, 430, 170, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void playMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseMoved

    }//GEN-LAST:event_playMouseMoved

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed

    }//GEN-LAST:event_playActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void howToPlayMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howToPlayMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_howToPlayMouseMoved

    private void howToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_howToPlayActionPerformed

    private void scoresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoresMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_scoresMouseMoved

    private void scoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton howToPlay;
    private javax.swing.JButton play;
    private javax.swing.JButton scores;
    // End of variables declaration//GEN-END:variables
}
